server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/StockManagement
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: stock-management-api

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
