server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/StockManagement
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: stock-management-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        auto-startup: true
  jackson:
    default-property-inclusion: non_null

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
  files:
    uploadDir: ${UPLOAD_DIR:src/main/resources/static/images/uploads}