spring:
  datasource:
    url: jdbc:h2:mem:testDatabase
    username: h2
    password: testDatabase
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

